### ISSUE TITLE
When converting string formula, getting  formula containing  ~@RESERVED_CNF_0

### ISSUE THREAD

**Issue by hwhh** [logic-ng/LogicNG#15]
When trying to parse the following string, the resulting CNF comes back with lots of @RESERVED_CNF_0 in it ?

(A & ~B | ~A & B) & (C & B & ~A & ~D & ~E | C & ~B & A & ~D & ~E | C & ~B & ~A & D & ~E | C & ~B & ~A & ~D & E | ~C & B & A & ~D & ~E | ~C & B & ~A & D & ~E | ~C & B & ~A & ~D & E | ~C & ~B & A & D & ~E | ~C & ~B & A & ~D & E | ~C & ~B & ~A & D & E) & (A & ~F | ~A & F) & (E & ~C | ~E & C)

**Comment by rouven-walter** [comment]
Hi @dangerdave1,
thank you, you just discovered a bug within the Quine-McCluskey algorithm. Instead of minimizing the given input formula, mistakenly the Tseitin transformed formula (containing auxiliary variables) was minimized and returned by Quine-McCluskey. We fixed this bug in the newest LogcNG version 1.4.1, released today. With the new release, the result is a minimized DNF without auxiliary variables.
