### ISSUE TITLE
Parallel computing

### ISSUE THREAD

**Issue by SPAstef** [logic-ng/LogicNG#24]
Hello,
I have an array of DNF strings I have to parse and minimize. I'd like to do that in parallel, since I need the EXACT minimization and also conversion to CNF, without addition of new variables, that is a pretty intense task. For that, I'd use a Java Parallel Stream, but unfortunately there are issues when trying to use a parser in parallel. Is there a way, without making the code too complicated (read: using parallel streams, not thread objects) to make it work in parallel?

**Comment by rouven-walter** [comment]
Sorry for the late reply.

You are right, parallel execution for the parser and the creation of formulas with a single `FormulaFactory` instance is an issue. The formula factory is currently not thread-safe and we would advise against using it for parallel execution.

One way to come up with parallel execution would be to create a formula factory instance for each DNF. Something like:
```java
String[] dnfs = ...
Arrays.stream(dnfs).parallel().forEach(dnf -> {
FormulaFactory f = new FormulaFactory();
  try {
    Formula formula = f.parse(dnf);
    // minimize formula here
    } catch (ParserException e) {
      e.printStackTrace();
     }
});
```
If you intend to put the resulting minimized formula's together (e.g. building the conjunction of them), you would have to import the formula's into a single formula factory instance before (see class `FormulaFactoryImporter`).

**Comment by SPAstef** [comment]
Thanks for the reply. For the purpose of my research I ended up having to make a dedicated C/CUDA framework to get satisfying performances (and running it on multi-GPU clusters), and in that particular instance I ended up using Espresso logic minimizer. Anyway, thanks again for the answer and, who knows, maybe in the future I'll need this library again (though I'm not a big fan of Java, eh 😅)

**Comment by rouven-walter** [comment]
Thank you for the feedback and good luck with your research. Next time we will respond faster 😄

**Comment by breandan** [comment]
I too have encountered many issues with parallelization and merging formula due to multiple threads using the same `FormulaFactory`. It would be convenient if there a were a way to build up immutable formulas using pure functions that do not create any external state like `FormulaFactory` does. Maybe one solution would be to have an `ImmutableFormula` class that wraps a `FormulaFactory` and a `Formula` object, and has a `FormulaFactory` as a constructor parameter, with an `IMPORT` merge strategy, i.e., where two formulas `f1.and(f2)` would use the first `FormulaFactory` to import the second - that would effectively give the same result as a pure formula operator.
