### ISSUE TITLE
Is it possible to have  saveState() and loadState() in MaxSATSolver? 

### ISSUE THREAD

**Issue by tendyliu** [logic-ng/LogicNG#36]
There is saveState() and loadState() functions in MiniSat,  it is very useful for not restart the solver from draft.

**Comment by SHildebrandt** [comment]
Sorry for the late response! 🙈 

Simple answer: We don't know and we haven't tried it yet.

Since the save/load-state functionality in MiniSat was *really* tricky to implement, we would expect that it will be quite an effort for MaxSAT solvers. Particularly testing the correctness for such functionality is really hard.

So from our side it will probably not be implemented in the near future.
